site:
  title: Halo
  url: https://docs.spring.io/spring-security/
asciidoc:
  attributes:
    page-pagination: true
content:
  sources:
    - url: https://github.com/JanusTeam/janus-docs
      branches: [master]
      
      start_path: adoc
    - url: https://github.com/spring-io/spring-generated-docs
      branches: [spring-projects/spring-security/*,spring-projects/spring-session/main]
    - url: https://github.com/spring-projects/spring-session
      branches: [main]
      start_path: spring-session-docs
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/halo-doc/antora-ui-halo/releases/download/halo/ui-bundle.zip
    snapshot: true

pipeline:
  extensions:
    - require: ./antora/extensions/root-component-name.js
