site:
  title: Spring
  url: https://docs.spring.io/spring-security/
  start_page: ROOT:ROOT:index.adoc
asciidoc:
  attributes:
    page-pagination: true
content:
  sources:
    - url: https://github.com/spring-projects/spring-security
      branches: [main]
      version:
        '*/*/(*)' : '$1'
      start_path: docs
    - url: https://github.com/spring-io/spring-generated-docs
      branches: [spring-projects/spring-security/main,spring-projects/spring-session/main]
      version:
        '*/*/(*)' : '$1'
    - url: https://github.com/spring-projects/spring-session
      branches: [main]
      start_path: spring-session-docs
      version:
        '*/*/(*)' : '$1'
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true

pipeline:
  extensions:
    - require: ./antora/extensions/root-component-name.js
    - require: ./antora/extensions/dynamic-component-version.js
