site:
  title: Spring
  start_page: framework::index.adoc
asciidoc:
  attributes:
    page-pagination: true
content:
  sources:
    - url: https://github.com/rwinch/spring-framework
      branches: antora-2.x
      start_path: src/docs/antora
    - url: https://github.com/rwinch/spring-security
      branches: [antora-2.x,6.0.x-antora-2.x]
      start_path: docs
    - url: https://github.com/rwinch/spring-session
      branches: [antora-2.x]
      start_path: spring-session-docs
ui:
  bundle:
    url: https://github.com/rwinch/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
