site:
  title: Spring
  start_page: security:ROOT:index.adoc
asciidoc:
  attributes:
    page-pagination: true
content:
  sources:
    - url: https://github.com/rwinch/spring-security
      branches: [antora/main,antora/5.5.x]
      start_path: docs
    - url: https://github.com/rwinch/spring-security-docs-generated
      branches: [spring-security/main,spring-session/main]
    - url: https://github.com/rwinch/spring-session
      branches: [antora/main]
      start_path: spring-session-docs
ui:
  bundle:
    url: https://github.com/rwinch/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
