site:
  title: Spring
  start_page: security:ROOT:index.adoc
asciidoc:
  attributes:
    page-pagination: true
content:
  sources:
    - url: https://github.com/spring-projects/spring-security
      branches: [main]
      start_path: docs
    - url: https://github.com/rwinch/spring-generated-docs
      branches: [spring-security/main,spring-session/main]
    - url: https://github.com/spring-projects/spring-session
      branches: [main]
      start_path: spring-session-docs
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
