site:
  title: Spring
  start_page: component-b::index.adoc
asciidoc:
  attributes:
    page-pagination: true
content:
  sources:
    - url: https://gitlab.com/antora/demo/demo-component-a.git
      branches: master
    - url: https://gitlab.com/antora/demo/demo-component-b.git
      branches: [v2.0, v1.0]
      start_path: docs
ui:
  bundle:
    url: ./ui-theme/ui-bundle.zip
    snapshot: true

pipeline:
  extensions:
    - require: ./antora/extensions/root-component-name.js
