site:
  title: Spring
  start_page: security:ROOT:index.adoc
content:
  sources:
    - url: ../../spring-projects/spring-security
      branches: [HEAD]
      start_path: docs
    - url: ../spring-generated-docs
      branches: [spring-security/main,spring-session/main]
    - url: ../../spring-projects/spring-session
      branches: HEAD
      start_path: spring-session-docs
ui:
  bundle:
    url: ../../spring-io/antora-ui-spring/build/ui-bundle.zip
    snapshot: true
